version: "3.9"

services:
  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../tryit-backend/tryit/static:/usr/share/nginx/static:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
